### ISSUE TITLE
Error in compile

### ISSUE THREAD

**Issue by spygineer** [BenVlodgi/BEE2.4#119]
Hello! I got an error when i tried to compile the source files.

Traceback (most recent call last):
  File "D:\Steam\SteamApps\common\Portal 2\portal2_dlc2\bee2.4\src\compile_BEE2.py", line 3, in <module>
    import utils
  File "D:\Steam\SteamApps\common\Portal 2\portal2_dlc2\bee2.4\src\utils.py", line 225
    def clean_line(line: str):
                       ^
SyntaxError: invalid syntax
>>> 

Well i'm new at python so maybe that's the problem,if i did some thing wrong,please tell me how to do it.

**Comment by TeamSpen210** [comment]
You'll need to use Python 3.4 at least to compile. You also need Pillow and Pygame for the application.

**Comment by spygineer** [comment]
ok,thanks a lot!
