### ISSUE TITLE
Prl20 Bug: Building Chambers Causes "Failure To Compile" 

### ISSUE THREAD

**Issue by LautaroL20** [BenVlodgi/BEE2.4#301]
```
Lautaro unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 99 (ms)

VBSP failed.

[I] vbsp: BEE2.4.0pr20 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting SP Exit to 1
[I] vbsp: Setting SP Entry to 1
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] cond.core: Checking Conditions...
[I] cond.catwalks: Starting catwalk generator...
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] vbsp: Elevator type: FORCE
[I] voiceLine: Adding Voice Lines!
[W] BEE2_config: Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config: Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voiceLine: Quote events: []
[I] voiceLine: No responses data..
[I] voiceLine: 0 Mid quotes
[I] voiceLine: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: Y
[I] vbsp: Done!
[I] vbsp: Added Screenshot Logic
[I] cond.core: Map has attributes: ['spawn_dual']
[I] cond.core: instanceLocs cache: CacheInfo(hits=2180, misses=248, maxsize=256, currsize=248)
[I] cond.core: Style Vars: {'fixfizzlerbump': False, 'allowgoomist': True, 'multiversecave': True, 'nomidvoices': False, 'bee_show_trigger': True, 'unlockdefault': False}
[I] cond.core: Global instances: {'instances/BEE2/clean/global_ents.vmf'}
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3852, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 3449, in make_packlist
  File "F:\Git\BEE2.4\src\property_parser.py", line 278, in parse
  File "F:\Git\BEE2.4\src\property_parser.py", line 150, in read_flag
property_parser.KeyValError: Extra text after line: "models/BEE2/props_p1/radio_clean.mdl"
Error occured on line 11, with file "bee2/pack_list.cfg"
```

**Comment by LautaroL20** [comment]
All styles causes "Failures". It seems Pre-release 20 is broken.
