### ISSUE TITLE
bee2 pre3 bug hunt

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BenVlodgi/BEE2.4#48]
it's time for a bug hunt, list any bugs you find in the new bee2 pre3 below here. list format as bug description, conditions that cause it, and then compiler error (if any)

- [x] many custom items like HEP's have blue and purple checkboard textures or show error's in game in clean style.
- [x] sometimes dragging a item from the selection in the palette of bee2 causes it to be replaced by the wrong item and dragging out the wrong item causes it to be replaced by the correct one.
- [X] changing the music to "TEST" in the new bee2 in the default clean style causes PTI to give a compile error. Recommend checking all the songs to see which ones cause errors. 
```
VBSP failed.
Config "../config\config.cfg" not found! Using defaults...
BEE2 VBSP hook initiallised.
Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
Loading settings...
{}
Settings Loaded!
PeTI map detected!
Parsing Map...
Parsing complete!
Game Mode: SP
Is Preview: True
"ITEM_PISTON_PLAT" not a valid item!
Editing Instances...
Checking Conditions...
Map has attributes:  ['floorbutton', 'weightedbutton', 'dualportalgun']
Style Vars: {'doorcameras': False}
Global instances:  ['instances/BEE2/clean/global_ents.vmf']
Adding Music...
Adding Global PTI Ents
Editing Other Entities...
Editing Brushes...
Editing Overlays...
Editing Triggers...
Editing Brush Entities...
Editing WorldSpawn
SP
Adding Singleplayer voice lines!
Adding Voice!
Config "bee2\SP.cfg" not found! Using defaults...
Config "bee2\MID_SP.cfg" not found! Using defaults...
Adding Base instance!
Generic True
Emancipation Grill False
Deadly False
Sentry Turret False
Discouragement Beam False
Conversion Gel False
Aerial Faith Plate False
Hard Light Bridge False
Propulsion Gel False
Mashy Spike Plate False
High Energy Pellets False
Reflection Gel False
Pneumatic Diversty Vent False
Paint Fizzler False
Sendificator False
Timer value:  -3
Chosen: [Property('instance', [Property('name', 'Federal Regulations'), Property('id', 'GENERIC_1'), Property('trans', 'Federal regulations require me to warn you that this next test chamber... is looking pretty good.'), Property('choreo', 'scenes/npc/glados/a2_triple_laser01.vcd')])]
Generic True
Deadly False
Aerial Faith Plate False
Repulsion Gel False
Propulsion Gel False
Timer value:  -3
Chosen: [Property('instance', [Property('name', 'Waddle Over To The Elevator'), Property('id', 'GENERIC_1'), Property('trans', "Waddle over to the elevator and we'll continue the testing."), Property('choreo', 'scenes/npc/glados/testchambermisc12.vcd')]), Property('instance', [Property('name', 'Mildly Impressive'), Property('id', 'GENERIC_2'), Property('trans', 'That was genuinely mildly impressive.'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard01.vcd')]), Property('instance', [Property('name', 'Statistically Speaking...'), Property('id', 'GENERIC_3'), Property('trans', 'You are playing above the global average. Statistically speaking, there are actually people playing worse than you.'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard20.vcd')]), Property('instance', [Property('name', 'Very Not Completely Bad'), Property('id', 'GENERIC_4'), Property('trans', 'Very not completely bad.'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard23.vcd')]), Property('instance', [Property('name', 'Maybe I Was Wrong'), Property('id', 'GENERIC_5'), Property('trans', '[impressed] Maybe I was wrong about you.'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard07.vcd')]), Property('instance', [Property('name', 'Impressive'), Property('trans', 'Impressive.'), Property('id', 'GENERIC_6'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard06.vcd')]), Property('instance', [Property('name', 'Congratulations'), Property('trans', 'Congratulations.'), Property('id', 'GENERIC_7'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard03.vcd')])]
mid quotes:  []
Done!
Saving New Map...
Complete!
Calling original VBSP...
"C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf"
Valve Software - vbsp.exe (Aug 26 2014)
4 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file BEE2/music/a4_tbeam_intro.vmf
VBSP failed! (1)
```
- P-body and atlas have wrong portal guns in single player
- changing to BTS style causes PTI compile error. 
```
VBSP failed.
Config "../config\config.cfg" not found! Using defaults...
BEE2 VBSP hook initiallised.
Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
Loading settings...
{'side': ['instances/BEE2/bts/sky/edge_1.vmf', 'instances/BEE2/bts/sky/edge_2.vmf', 'instances/BEE2/bts/sky/edge_3.vmf', ''], 'pillar': ['instances/BEE2/bts/sky/pillar_1.vmf', 'instances/BEE2/bts/sky/pillar_1.vmf', 'instances/BEE2/bts/sky/pillar_1.vmf', 'instances/BEE2/bts/sky/pillar_1.vmf', ''], 'height': 386, 'tex_sky': 'TOOLS/TOOLSSKYBOX', 'off_x': -8192, 'tele_ref': '@sky_tele_ref', 'off_y': 0, 'tex_goo': 'nature/toxicslime_puzzlemaker_cheap', 'should_tele': True, 'tele_dest': '@sky_tele_targ'}
Settings Loaded!
PeTI map detected!
Parsing Map...
Parsing complete!
Game Mode: ERR
Is Preview: ERR
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp.py", line 1474, in <module>
  File "vbsp.py", line 1438, in main
  File "vbsp.py", line 451, in get_map_info
Exception: Unknown game mode - Map missing exit room!
```
- [x] portal 1 exit door is wrong type of door
- [x] 1980's style gives compile error in PTI when used.
```
VBSP failed.
Config "../config\config.cfg" not found! Using defaults...
BEE2 VBSP hook initiallised.
Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
Loading settings...
{}
Settings Loaded!
PeTI map detected!
Parsing Map...
Parsing complete!
Game Mode: SP
Is Preview: True
"ITEM_PISTON_PLAT" not a valid item!
Editing Instances...
Checking Conditions...
adding overlay instances/BEE2/50s/sphere_sp/entry_corridor_2/no_bluegel.vmf
adding overlay instances/BEE2/50s/sphere_sp/entry_corridor_2/no_deadly.vmf
adding overlay instances/BEE2/50s/sphere_sp/entry_corridor_2/no_funnel.vmf
Map has attributes:  ['dualportalgun']
Style Vars: {}
Global instances:  ['instances/BEE2/80s/global_ents.vmf']
Adding Music...
Adding Global PTI Ents
Editing Other Entities...
Changing goo sides...
Done!
Editing Brushes...
Editing Overlays...
Editing Triggers...
Editing Brush Entities...
Editing WorldSpawn
SP
Adding Singleplayer voice lines!
Adding Voice!
Config "bee2\SP.cfg" not found! Using defaults...
Config "bee2\MID_SP.cfg" not found! Using defaults...
Adding Base instance!
Generic True
Emancipation Grill False
Deadly False
Sentry Turret False
Discouragement Beam False
Conversion Gel False
Aerial Faith Plate False
Hard Light Bridge False
Propulsion Gel False
Mashy Spike Plate False
High Energy Pellets False
Reflection Gel False
Pneumatic Diversty Vent False
Paint Fizzler False
Sendificator False
Timer value:  -3
Chosen: [Property('instance', [Property('name', 'Federal Regulations'), Property('id', 'GENERIC_1'), Property('trans', 'Federal regulations require me to warn you that this next test chamber... is looking pretty good.'), Property('choreo', 'scenes/npc/glados/a2_triple_laser01.vcd')])]
Generic True
Deadly False
Aerial Faith Plate False
Repulsion Gel False
Propulsion Gel False
Timer value:  -3
Chosen: [Property('instance', [Property('name', 'Waddle Over To The Elevator'), Property('id', 'GENERIC_1'), Property('trans', "Waddle over to the elevator and we'll continue the testing."), Property('choreo', 'scenes/npc/glados/testchambermisc12.vcd')]), Property('instance', [Property('name', 'Mildly Impressive'), Property('id', 'GENERIC_2'), Property('trans', 'That was genuinely mildly impressive.'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard01.vcd')]), Property('instance', [Property('name', 'Statistically Speaking...'), Property('id', 'GENERIC_3'), Property('trans', 'You are playing above the global average. Statistically speaking, there are actually people playing worse than you.'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard20.vcd')]), Property('instance', [Property('name', 'Very Not Completely Bad'), Property('id', 'GENERIC_4'), Property('trans', 'Very not completely bad.'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard23.vcd')]), Property('instance', [Property('name', 'Maybe I Was Wrong'), Property('id', 'GENERIC_5'), Property('trans', '[impressed] Maybe I was wrong about you.'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard07.vcd')]), Property('instance', [Property('name', 'Impressive'), Property('trans', 'Impressive.'), Property('id', 'GENERIC_6'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard06.vcd')]), Property('instance', [Property('name', 'Congratulations'), Property('trans', 'Congratulations.'), Property('id', 'GENERIC_7'), Property('choreo', 'scenes/npc/glados/dlc1_leaderboard03.vcd')])]
mid quotes:  []
Done!
Saving New Map...
Complete!
Calling original VBSP...
"C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf"
Valve Software - vbsp.exe (Aug 26 2014)
4 threads
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Error! Variable "$envmap" is multiply defined in material "metal/underground_wall_metal004a_bottom"!
Could not open instance file instances/BEE2/80s/indicator_panel.vmf
VBSP failed! (1)
```
- [x] selecting spawn at elevator spawns at door in default clean style

**Comment by TeamSpen210** [comment]
Can you be more specific? What style, and what compile error?

**Comment by ellingtonisland** [comment]
updated recently

**Comment by TeamSpen210** [comment]
In future, could you just put one bug per issue? Item/style bugs should go in [BEE2-items](TeamSpen210/BEE2-items/issues).

 It's not possible to change the portalgun or portalgun colours in a map without a sourcemod. Everything else I'll fix.

**Comment by ellingtonisland** [comment]
closed
